[theme]
name = "solarized-light"
[theme.overrides]
separator="\uE0C2"
#idle_bg="#333333"
#good_bg="#333333"
#warning_bg="#333333"
#info_bg="#333333"
#critical_bg="#333333"
#separator_bg="#333333"

[icons]
name = "awesome"

[[block]]
block = "net"
device = "wlp0s20u1"
ssid = false
signal_strength = true
ip = true
speed_up = false
interval = 2
use_bits = false
hide_missing = true
hide_inactive = true

[[block]]
block = "custom"
command = "bash /home/annahri/.local/bin/corona.sh"
interval = 100

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

#[[block]]
#block = "keyboard_layout"
#driver = "setxkbmap"
#interval = 15

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %v %R"

#[[block]]
#block = "custom"
#command = "echo net"
#on_click = "st -e nmtui"
